# Import Library

In [1]:

import pandas as pd
import numpy as np

from sklearn.preprocessing import LabelEncoder
from sklearn.model_selection import train_test_split

#  DATA LOADING

In [2]:
df= pd.read_csv('laptop_cleaned2.csv')
df

,Unnamed: 0,Name,Brand,Price,Rating,Processor_brand,Processor_name,Processor_variant,Processor_gen,Core_per_processor,...,Graphics_name,Graphics_brand,Graphics_GB,Graphics_integreted,Display_size_inches,Horizontal_pixel,Vertical_pixel,ppi,Touch_screen,Operating_system
0,0,HP Victus 15-fb0157AX Gaming Laptop (AMD Ryzen...,HP,50399,4.30,AMD,AMD Ryzen 5,5600H,5.0,6.0,...,AMD Radeon RX 6500M,AMD,4.0,False,15.6,1920,1080,141.21,True,Windows 11 OS
1,1,Lenovo V15 G4 â€Ž82YU00W7IN Laptop (AMD Ryzen 3 ...,Lenovo,26690,4.45,AMD,AMD Ryzen 3,7320U,7.0,4.0,...,AMD Radeon Graphics,AMD,NaN,False,15.6,1920,1080,141.21,False,Windows 11 OS
2,2,HP 15s-fq5007TU Laptop (12th Gen Core i3/ 8GB/...,HP,37012,4.65,Intel,Intel Core i3,1215U,12.0,6.0,...,Intel UHD Graphics,Intel,NaN,False,15.6,1920,1080,141.21,False,Windows 11 OS
3,3,Samsung Galaxy Book2 Pro 13 Laptop (12th Gen C...,Samsung,69990,4.75,Intel,Intel Core i5,1240P,12.0,12.0,...,Intel Iris Xe Graphics,Intel,NaN,False,13.3,1080,1920,165.63,False,Windows 11 OS
4,4,Tecno Megabook T1 Laptop (11th Gen Core i3/ 8G...,Tecno,23990,4.25,Intel,Intel Core i3,1115G4,11.0,2.0,...,Intel UHD Graphics,Intel,NaN,False,15.6,1920,1080,141.21,False,Windows 11 OS
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1015,1015,MSI Creator Z17 HX Studio A13V Laptop,MSI,247999,4.45,Intel,Intel Core i9,13900H,13.0,14.0,...,NVIDIA GeForce RTX 4070,NVIDIA,8.0,False,17.0,2560,1600,177.58,False,Windows 11 OS
1016,1016,MSI Stealth 16 Mercedes AMG Motorsport A13V Ga...,MSI,292990,4.20,Intel,Intel Core i9,13900H,13.0,14.0,...,NVIDIA GeForce RTX 4070,NVIDIA,8.0,False,16.0,3840,2400,283.02,False,Windows 11 OS
1017,1017,HP Victus 15-fb0131AX Gaming Laptop (AMD Ryzen...,HP,58800,4.40,AMD,AMD Ryzen 5,5600H,5.0,6.0,...,AMD Radeon RX 5600M,AMD,4.0,False,15.6,1920,1080,141.21,False,Windows 11 OS
1018,1018,Asus Vivobook 16 2023 M1605YA-MB521WS Laptop (...,Asus,54999,4.25,AMD,AMD Ryzen 5,7530U,7.0,6.0,...,AMD Radeon AMD,AMD,NaN,False,16.0,1920,1200,141.51,False,Windows 11 OS
1019,1019,Dell Inspiron 7630 IC7630GHHRH001ORS1 2 in 1 L...,Dell,94490,4.05,Intel,Intel Core i5,1335U,13.0,10.0,...,Intel Iris Xe Graphics,Intel,NaN,False,16.0,1920,1200,141.51,True,Windows 11 OS

# Data Exploration

In [3]:
print(f"Number of Rows: {df.shape[0]}\nNumber of Columns: {df.shape[1]}")

Number of Rows: 1020
Number of Columns: 29

In [4]:
df.head(2)

,Unnamed: 0,Name,Brand,Price,Rating,Processor_brand,Processor_name,Processor_variant,Processor_gen,Core_per_processor,...,Graphics_name,Graphics_brand,Graphics_GB,Graphics_integreted,Display_size_inches,Horizontal_pixel,Vertical_pixel,ppi,Touch_screen,Operating_system
0,0,HP Victus 15-fb0157AX Gaming Laptop (AMD Ryzen...,HP,50399,4.30,AMD,AMD Ryzen 5,5600H,5.0,6.0,...,AMD Radeon RX 6500M,AMD,4.0,False,15.6,1920,1080,141.21,True,Windows 11 OS
1,1,Lenovo V15 G4 â€Ž82YU00W7IN Laptop (AMD Ryzen 3 ...,Lenovo,26690,4.45,AMD,AMD Ryzen 3,7320U,7.0,4.0,...,AMD Radeon Graphics,AMD,NaN,False,15.6,1920,1080,141.21,False,Windows 11 OS

In [5]:
df.tail(2)

,Unnamed: 0,Name,Brand,Price,Rating,Processor_brand,Processor_name,Processor_variant,Processor_gen,Core_per_processor,...,Graphics_name,Graphics_brand,Graphics_GB,Graphics_integreted,Display_size_inches,Horizontal_pixel,Vertical_pixel,ppi,Touch_screen,Operating_system
1018,1018,Asus Vivobook 16 2023 M1605YA-MB521WS Laptop (...,Asus,54999,4.25,AMD,AMD Ryzen 5,7530U,7.0,6.0,...,AMD Radeon AMD,AMD,NaN,False,16.0,1920,1200,141.51,False,Windows 11 OS
1019,1019,Dell Inspiron 7630 IC7630GHHRH001ORS1 2 in 1 L...,Dell,94490,4.05,Intel,Intel Core i5,1335U,13.0,10.0,...,Intel Iris Xe Graphics,Intel,NaN,False,16.0,1920,1200,141.51,True,Windows 11 OS

In [6]:
df.describe()

,Unnamed: 0,Price,Rating,Processor_gen,Core_per_processor,Total_processor,Execution_units,Low_Power_Cores,Energy_Efficient_Units,Threads,RAM_GB,Storage_capacity_GB,Graphics_GB,Display_size_inches,Horizontal_pixel,Vertical_pixel,ppi
count,1020.000000,1020.000000,1020.000000,891.000000,1008.000000,573.000000,573.000000,1020.000000,1020.000000,972.000000,1020.000000,1020.000000,368.000000,1020.000000,1020.000000,1020.000000,1020.000000
mean,509.500000,82063.474510,4.373676,10.450056,8.572421,3.926702,6.998255,0.086275,0.043137,12.817901,13.992157,627.733333,5.940217,15.163775,2035.512745,1214.019608,157.178265
std,294.592939,66502.150607,0.233295,2.966579,4.375012,1.954429,2.680217,0.406531,0.203266,5.677459,7.189564,316.911679,2.667130,1.001537,409.209289,306.863086,33.585713
min,0.000000,8000.000000,3.950000,1.000000,2.000000,1.000000,4.000000,0.000000,0.000000,2.000000,2.000000,32.000000,2.000000,11.600000,1080.000000,768.000000,100.450000
25%,254.750000,43990.000000,4.200000,7.000000,6.000000,2.000000,4.000000,0.000000,0.000000,8.000000,8.000000,512.000000,4.000000,14.000000,1920.000000,1080.000000,141.210000
50%,509.500000,63689.500000,4.350000,12.000000,8.000000,4.000000,8.000000,0.000000,0.000000,12.000000,16.000000,512.000000,6.000000,15.600000,1920.000000,1080.000000,141.210000
75%,764.250000,94990.000000,4.550000,13.000000,10.000000,6.000000,8.000000,0.000000,0.000000,16.000000,16.000000,512.000000,8.000000,15.600000,1920.000000,1200.000000,161.730000
max,1019.000000,599990.000000,4.750000,14.000000,24.000000,12.000000,16.000000,2.000000,1.000000,32.000000,64.000000,4000.000000,16.000000,18.000000,3840.000000,2560.000000,337.930000

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 29 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              1020 non-null   int64
 1   Name                    1020 non-null   object
 2   Brand                   1020 non-null   object
 3   Price                   1020 non-null   int64
 4   Rating                  1020 non-null   float64
 5   Processor_brand         1020 non-null   object
 6   Processor_name          1020 non-null   object
 7   Processor_variant       996 non-null    object
 8   Processor_gen           891 non-null    float64
 9   Core_per_processor      1008 non-null   float64
 10  Total_processor         573 non-null    float64
 11  Execution_units         573 non-null    float64
 12  Low_Power_Cores         1020 non-null   float64
 13  Energy_Efficient_Units  1020 non-null   int64
 14  Threads                 972 non-null    float64
 15  RAM_GB                  1020 non-null   int64
 16  RAM_type                998 non-null    object
 17  Storage_capacity_GB     1020 non-null   int64
 18  Storage_type            1020 non-null   object
 19  Graphics_name           1018 non-null   object
 20  Graphics_brand          1018 non-null   object
 21  Graphics_GB             368 non-null    float64
 22  Graphics_integreted     1018 non-null   object
 23  Display_size_inches     1020 non-null   float64
 24  Horizontal_pixel        1020 non-null   int64
 25  Vertical_pixel          1020 non-null   int64
 26  ppi                     1020 non-null   float64
 27  Touch_screen            1020 non-null   bool
 28  Operating_system        1020 non-null   object
dtypes: bool(1), float64(10), int64(7), object(11)
memory usage: 224.2+ KB

In [8]:
for i in df.columns:
    print(i)

Unnamed: 0
Name
Brand
Price
Rating
Processor_brand
Processor_name
Processor_variant
Processor_gen
Core_per_processor
Total_processor
Execution_units
Low_Power_Cores
Energy_Efficient_Units
Threads
RAM_GB
RAM_type
Storage_capacity_GB
Storage_type
Graphics_name
Graphics_brand
Graphics_GB
Graphics_integreted
Display_size_inches
Horizontal_pixel
Vertical_pixel
ppi
Touch_screen
Operating_system

In [9]:
df.count()

Unnamed: 0                1020
Name                      1020
Brand                     1020
Price                     1020
Rating                    1020
Processor_brand           1020
Processor_name            1020
Processor_variant          996
Processor_gen              891
Core_per_processor        1008
Total_processor            573
Execution_units            573
Low_Power_Cores           1020
Energy_Efficient_Units    1020
Threads                    972
RAM_GB                    1020
RAM_type                   998
Storage_capacity_GB       1020
Storage_type              1020
Graphics_name             1018
Graphics_brand            1018
Graphics_GB                368
Graphics_integreted       1018
Display_size_inches       1020
Horizontal_pixel          1020
Vertical_pixel            1020
ppi                       1020
Touch_screen              1020
Operating_system          1020
dtype: int64

In [10]:
df['Brand'].unique()

array(['HP', 'Lenovo', 'Samsung', 'Tecno', 'Xiaomi', 'Dell', 'Asus',
       'Wings', 'Apple', 'Zebronics', 'Gigabyte', 'Acer', 'MSI',
       'Infinix', 'Honor', 'Colorful', 'iBall', 'Walker', 'Chuwi', 'ASUS',
       'Ultimus', 'Jio', 'Microsoft', 'Primebook', 'Ninkear', 'Avita',
       'Huawei', 'Fujitsu', 'LG', 'Razer', 'AXL'], dtype=object)

In [11]:
df.nunique()

Unnamed: 0                1020
Name                      1020
Brand                       31
Price                      561
Rating                      17
Processor_brand              7
Processor_name              36
Processor_variant          125
Processor_gen               13
Core_per_processor          12
Total_processor              8
Execution_units              5
Low_Power_Cores              2
Energy_Efficient_Units       2
Threads                     14
RAM_GB                      10
RAM_type                    12
Storage_capacity_GB         10
Storage_type                 4
Graphics_name              136
Graphics_brand               7
Graphics_GB                  6
Graphics_integreted          2
Display_size_inches         22
Horizontal_pixel            22
Vertical_pixel              22
ppi                         62
Touch_screen                 2
Operating_system            13
dtype: int64

In [12]:
df.isnull().sum()

Unnamed: 0                  0
Name                        0
Brand                       0
Price                       0
Rating                      0
Processor_brand             0
Processor_name              0
Processor_variant          24
Processor_gen             129
Core_per_processor         12
Total_processor           447
Execution_units           447
Low_Power_Cores             0
Energy_Efficient_Units      0
Threads                    48
RAM_GB                      0
RAM_type                   22
Storage_capacity_GB         0
Storage_type                0
Graphics_name               2
Graphics_brand              2
Graphics_GB               652
Graphics_integreted         2
Display_size_inches         0
Horizontal_pixel            0
Vertical_pixel              0
ppi                         0
Touch_screen                0
Operating_system            0
dtype: int64

# Data Pre-Processing

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 29 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              1020 non-null   int64
 1   Name                    1020 non-null   object
 2   Brand                   1020 non-null   object
 3   Price                   1020 non-null   int64
 4   Rating                  1020 non-null   float64
 5   Processor_brand         1020 non-null   object
 6   Processor_name          1020 non-null   object
 7   Processor_variant       996 non-null    object
 8   Processor_gen           891 non-null    float64
 9   Core_per_processor      1008 non-null   float64
 10  Total_processor         573 non-null    float64
 11  Execution_units         573 non-null    float64
 12  Low_Power_Cores         1020 non-null   float64
 13  Energy_Efficient_Units  1020 non-null   int64
 14  Threads                 972 non-null    float64
 15  RAM_GB                  1020 non-null   int64
 16  RAM_type                998 non-null    object
 17  Storage_capacity_GB     1020 non-null   int64
 18  Storage_type            1020 non-null   object
 19  Graphics_name           1018 non-null   object
 20  Graphics_brand          1018 non-null   object
 21  Graphics_GB             368 non-null    float64
 22  Graphics_integreted     1018 non-null   object
 23  Display_size_inches     1020 non-null   float64
 24  Horizontal_pixel        1020 non-null   int64
 25  Vertical_pixel          1020 non-null   int64
 26  ppi                     1020 non-null   float64
 27  Touch_screen            1020 non-null   bool
 28  Operating_system        1020 non-null   object
dtypes: bool(1), float64(10), int64(7), object(11)
memory usage: 224.2+ KB

## Dealing with null values

In [14]:
def fillNaMean(cols):
    for i in cols:
        df[i] = df[i].fillna(df[i].mean())

columns = ['Rating', 'Processor_gen', 'Core_per_processor', 'Total_processor', 'Execution_units', 'Low_Power_Cores', 'Threads', 'Graphics_GB', 'Display_size_inches', 'ppi']
fillNaMean(columns)

In [15]:
def fillNaMode(cols):
    for i in cols:
        df[i] = df[i].fillna(df[i].mode()[0])

columns = ['Name', 'Brand', 'Processor_brand', 'Processor_brand', 'Processor_variant', 'RAM_type', 'Storage_type', 'Graphics_name', 'Graphics_brand', 'Graphics_integreted', 'Operating_system']
fillNaMode(columns)

In [16]:
df.isnull().sum()

Unnamed: 0                0
Name                      0
Brand                     0
Price                     0
Rating                    0
Processor_brand           0
Processor_name            0
Processor_variant         0
Processor_gen             0
Core_per_processor        0
Total_processor           0
Execution_units           0
Low_Power_Cores           0
Energy_Efficient_Units    0
Threads                   0
RAM_GB                    0
RAM_type                  0
Storage_capacity_GB       0
Storage_type              0
Graphics_name             0
Graphics_brand            0
Graphics_GB               0
Graphics_integreted       0
Display_size_inches       0
Horizontal_pixel          0
Vertical_pixel            0
ppi                       0
Touch_screen              0
Operating_system          0
dtype: int64

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 29 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Unnamed: 0              1020 non-null   int64
 1   Name                    1020 non-null   object
 2   Brand                   1020 non-null   object
 3   Price                   1020 non-null   int64
 4   Rating                  1020 non-null   float64
 5   Processor_brand         1020 non-null   object
 6   Processor_name          1020 non-null   object
 7   Processor_variant       1020 non-null   object
 8   Processor_gen           1020 non-null   float64
 9   Core_per_processor      1020 non-null   float64
 10  Total_processor         1020 non-null   float64
 11  Execution_units         1020 non-null   float64
 12  Low_Power_Cores         1020 non-null   float64
 13  Energy_Efficient_Units  1020 non-null   int64
 14  Threads                 1020 non-null   float64
 15  RAM_GB                  1020 non-null   int64
 16  RAM_type                1020 non-null   object
 17  Storage_capacity_GB     1020 non-null   int64
 18  Storage_type            1020 non-null   object
 19  Graphics_name           1020 non-null   object
 20  Graphics_brand          1020 non-null   object
 21  Graphics_GB             1020 non-null   float64
 22  Graphics_integreted     1020 non-null   bool
 23  Display_size_inches     1020 non-null   float64
 24  Horizontal_pixel        1020 non-null   int64
 25  Vertical_pixel          1020 non-null   int64
 26  ppi                     1020 non-null   float64
 27  Touch_screen            1020 non-null   bool
 28  Operating_system        1020 non-null   object
dtypes: bool(2), float64(10), int64(7), object(10)
memory usage: 217.3+ KB

## Dropping Irrelevant Columns

In [18]:
df.drop('Graphics_integreted', axis=1, inplace=True)
df.drop('Rating', axis=1, inplace=True)
df.drop('Core_per_processor', axis=1, inplace=True)
df.drop('Total_processor', axis=1, inplace=True)
df.drop('Execution_units', axis=1, inplace=True)
df.drop('Low_Power_Cores', axis=1, inplace=True)
df.drop('Energy_Efficient_Units', axis=1, inplace=True)
df.drop('Threads', axis=1, inplace=True)
df.drop('Horizontal_pixel', axis=1, inplace=True)
df.drop('Vertical_pixel', axis=1, inplace=True)
df.drop('ppi', axis=1, inplace=True)

In [19]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           1020 non-null   int64
 1   Name                 1020 non-null   object
 2   Brand                1020 non-null   object
 3   Price                1020 non-null   int64
 4   Processor_brand      1020 non-null   object
 5   Processor_name       1020 non-null   object
 6   Processor_variant    1020 non-null   object
 7   Processor_gen        1020 non-null   float64
 8   RAM_GB               1020 non-null   int64
 9   RAM_type             1020 non-null   object
 10  Storage_capacity_GB  1020 non-null   int64
 11  Storage_type         1020 non-null   object
 12  Graphics_name        1020 non-null   object
 13  Graphics_brand       1020 non-null   object
 14  Graphics_GB          1020 non-null   float64
 15  Display_size_inches  1020 non-null   float64
 16  Touch_screen         1020 non-null   bool
 17  Operating_system     1020 non-null   object
dtypes: bool(1), float64(3), int64(4), object(10)
memory usage: 136.6+ KB

In [20]:

def changeFloattoInt64(cols):
    for i in cols:
        df[i] = df[i].astype('int64')

columns = ['Processor_gen', 'Graphics_GB', 'Display_size_inches','Touch_screen']
changeFloattoInt64(columns)

In [21]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           1020 non-null   int64
 1   Name                 1020 non-null   object
 2   Brand                1020 non-null   object
 3   Price                1020 non-null   int64
 4   Processor_brand      1020 non-null   object
 5   Processor_name       1020 non-null   object
 6   Processor_variant    1020 non-null   object
 7   Processor_gen        1020 non-null   int64
 8   RAM_GB               1020 non-null   int64
 9   RAM_type             1020 non-null   object
 10  Storage_capacity_GB  1020 non-null   int64
 11  Storage_type         1020 non-null   object
 12  Graphics_name        1020 non-null   object
 13  Graphics_brand       1020 non-null   object
 14  Graphics_GB          1020 non-null   int64
 15  Display_size_inches  1020 non-null   int64
 16  Touch_screen         1020 non-null   int64
 17  Operating_system     1020 non-null   object
dtypes: int64(8), object(10)
memory usage: 143.6+ KB

In [22]:
df_clean = df.copy()

In [23]:
def encodeCols(cols):
    for i in cols:
        temp = pd.DataFrame({i:df[i].unique()})
        data_LE = LabelEncoder()
        data_LE.fit(np.ravel(temp))

        df_clean[i] = data_LE.transform(df[i])

columns = ['Name', 'Brand', 'Processor_brand', 'Processor_name', 'Processor_variant', 'RAM_type', 'Storage_type', 'Graphics_name', 'Graphics_brand', 'Operating_system']
encodeCols(columns)

In [24]:
df_clean['Brand'].unique()

array([11, 17, 23, 24, 28,  8,  4, 27,  3, 29, 10,  2, 18, 14, 12,  7, 30,
       26,  6,  0, 25, 15, 19, 21, 20,  5, 13,  9, 16, 22,  1])

In [25]:
df_clean.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1020 entries, 0 to 1019
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Unnamed: 0           1020 non-null   int64
 1   Name                 1020 non-null   int32
 2   Brand                1020 non-null   int32
 3   Price                1020 non-null   int64
 4   Processor_brand      1020 non-null   int32
 5   Processor_name       1020 non-null   int32
 6   Processor_variant    1020 non-null   int32
 7   Processor_gen        1020 non-null   int64
 8   RAM_GB               1020 non-null   int64
 9   RAM_type             1020 non-null   int32
 10  Storage_capacity_GB  1020 non-null   int64
 11  Storage_type         1020 non-null   int32
 12  Graphics_name        1020 non-null   int32
 13  Graphics_brand       1020 non-null   int32
 14  Graphics_GB          1020 non-null   int64
 15  Display_size_inches  1020 non-null   int64
 16  Touch_screen         1020 non-null   int64
 17  Operating_system     1020 non-null   int32
dtypes: int32(10), int64(8)
memory usage: 103.7 KB

In [26]:
df_clean.to_csv(r'cleaned-data.csv', index= False, header = True)

In [27]:
df_clean.head(2)

,Unnamed: 0,Name,Brand,Price,Processor_brand,Processor_name,Processor_variant,Processor_gen,RAM_GB,RAM_type,Storage_capacity_GB,Storage_type,Graphics_name,Graphics_brand,Graphics_GB,Display_size_inches,Touch_screen,Operating_system
0,0,580,11,50399,0,4,74,5,8,1,512,2,22,0,4,15,1,11
1,1,837,17,26690,0,3,87,7,8,7,512,2,19,0,5,15,0,11

# Data Splitting / Train-Test Split

In [30]:
X = df_clean.drop(columns=["Name", "Price"])
Y = df_clean["Price"]

X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=42)

print("Training set size:", X_train.shape)
print("Test set size:", X_test.shape)

Training set size: (816, 16)
Test set size: (204, 16)

# Training / Applying Classifier / Accuracy:

In [31]:
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score, mean_absolute_error

model = LinearRegression()
model.fit(X_train, y_train)

y_pred = model.predict(X_test)

r2 = r2_score(y_test, y_pred)
mae = mean_absolute_error(y_test, y_pred)

print(f"RÂ² Score (Accuracy): {r2:.2f}")
print(f"Mean Absolute Error: {mae:.2f}")

RÂ² Score (Accuracy): 0.78
Mean Absolute Error: 19588.39